export const styles = {
    pageContainer: {
      position: "relative",
      width: "100%",
      minHeight: "100vh",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      padding: "2rem",
      backgroundColor: "#f5f3ff",
    },
    container: {
      position: "relative",
      padding: "1.5rem",
      maxWidth: "90vw",
      width: "1200px",
      height: "auto",
      minHeight: "600px",
      margin: "0 auto",
      backgroundColor: "#eef2ff",
      color: "#312e81",
      fontFamily: "monospace, ui-monospace, SFMono-Regular",
      border: "6px solid #818cf8",
      borderRadius: "0.75rem",
      boxShadow: "0.75rem 0.75rem 0 0 rgba(129,140,248,0.5)",
      overflow: "visible",
      display: "flex",
      flexDirection: "column",
    },
    header: {
      borderBottom: "6px solid #818cf8",
      paddingBottom: "1.5rem",
      marginBottom: "1.5rem",
    },
    headerContent: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      gap: "1rem",
      marginBottom: "0.75rem",
    },
    title: {
      fontSize: "2.5rem",
      fontWeight: "bold",
      textAlign: "center",
      letterSpacing: "0.05em",
      color: "#7c3aed",
    },
    gradientBar1: {
      height: "0.75rem",
      width: "100%",
      background: "linear-gradient(to right, #c084fc, #f472b6, #c084fc)",
      marginTop: "0.75rem",
      borderRadius: "9999px",
    },
    gradientBar2: {
      height: "0.5rem",
      width: "100%",
      background: "linear-gradient(to right, #d8b4fe, #f9a8d4, #d8b4fe)",
      marginTop: "0.5rem",
      borderRadius: "9999px",
    },
    slideContainer: {
      flex: 1,
      position: "relative",
      backgroundColor: "white",
      borderRadius: "0.75rem",
      border: "3px solid #a5b4fc",
      padding: "1.5rem",
      display: "flex",
      flexDirection: "column",
      minHeight: "500px",
    },
    slide: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      padding: "1.5rem",
      opacity: 0,
      transition: "opacity 0.5s ease-in-out",
      display: "none",
      overflowY: "auto",
    },
    activeSlide: {
      opacity: 1,
      display: "block",
      position: "relative",
    },
    sectionTitle: {
      fontSize: "2rem",
      fontWeight: "600",
      marginBottom: "1.5rem",
      color: "#9333ea",
      letterSpacing: "0.05em",
      textAlign: "center",
    },
    paragraph: {
      fontSize: "1.25rem",
      lineHeight: "1.75",
      marginBottom: "1.5rem",
    },
    footer: {
      borderTop: "6px solid #818cf8",
      paddingTop: "1.5rem",
      marginTop: "1.5rem",
      display: "flex",
      justifyContent: "space-between",
    },
    footerLeft: {
      display: "flex",
      alignItems: "center",
    },
    footerRight: {
      display: "flex",
      alignItems: "center",
    },
    colorBlock: {
      width: "1.5rem",
      height: "1.5rem",
      marginRight: "0.75rem",
    },
    colorBlockRight: {
      width: "1.5rem",
      height: "1.5rem",
      marginLeft: "0.75rem",
    },
    footerText: {
      fontSize: "1rem",
      color: "#4338ca",
    },
    navButton: {
      position: "absolute",
      top: "50%",
      transform: "translateY(-50%)",
      width: "50px",
      height: "50px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#a5b4fc",
      color: "#312e81",
      border: "none",
      cursor: "pointer",
      zIndex: 10,
      borderRadius: "0",
      boxShadow: "0.25rem 0.25rem 0 0 rgba(79,70,229,0.5)",
      transition: "transform 0.1s ease-in-out, box-shadow 0.1s ease-in-out",
    },
    navButtonLeft: {
      left: "10px",
      borderRight: "4px solid #6366f1",
      borderBottom: "4px solid #6366f1",
    },
    navButtonRight: {
      right: "10px",
      borderLeft: "4px solid #6366f1",
      borderBottom: "4px solid #6366f1",
    },
    progressBar: {
      display: "flex",
      justifyContent: "center",
      gap: "0.75rem",
      marginTop: "0.75rem",
    },
    progressDot: {
      width: "1.25rem",
      height: "1.25rem",
      backgroundColor: "#c7d2fe",
      borderRadius: "0",
      cursor: "pointer",
      transition: "transform 0.2s ease",
    },
    activeDot: {
      backgroundColor: "#6366f1",
    },
    slideTitle: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: "2rem",
    },
    slideTitleNumber: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      width: "3rem",
      height: "3rem",
      backgroundColor: "#8b5cf6",
      color: "white",
      marginRight: "1rem",
      fontSize: "1.75rem",
      fontWeight: "bold",
    },
    windowsHeader: {
      backgroundColor: "#6366f1",
      color: "white",
      padding: "0.75rem 1.5rem",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      borderTopLeftRadius: "0.75rem",
      borderTopRightRadius: "0.75rem",
      marginBottom: "0.75rem",
      fontSize: "1.25rem",
    },
    windowsButtons: {
      display: "flex",
      gap: "0.75rem",
    },
    windowsButton: {
      width: "1.5rem",
      height: "1.5rem",
      borderRadius: "0",
      border: "1px solid white",
    },
    windowsContent: {
      padding: "0.75rem",
      height: "calc(100% - 3.5rem)",
      position: "relative",
      display: "flex",
      flexDirection: "column",
    },
    contentBox: {
      border: "2px dashed #a5b4fc",
      padding: "1.5rem",
      borderRadius: "0.75rem",
      marginBottom: "1.5rem",
      fontSize: "1.25rem",
    },
    contentBoxTitle: {
      color: "#7c3aed",
      marginBottom: "1rem",
      fontWeight: "bold",
      fontSize: "1.5rem",
    },
    contentList: {
      listStyleType: "square",
      paddingLeft: "2rem",
      lineHeight: "1.75",
    },
    input: {
      width: "100%",
      backgroundColor: "#eef2ff",
      border: "3px solid #a5b4fc",
      padding: "1rem",
      fontSize: "1.25rem",
      color: "#3730a3",
      fontFamily: "monospace, ui-monospace, SFMono-Regular",
      borderRadius: "0.75rem",
      outline: "none",
    },
}